"""
Vivado Tcl Server 安装模块

提供 Vivado 集成功能，包括：
- 自动检测 Vivado 安装路径
- 安装 Tcl Server 到 Vivado
- 卸载 Tcl Server
"""

import logging
import re
import sys
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Optional

if sys.platform == "win32":
    import winreg

logger = logging.getLogger(__name__)

DEFAULT_PORT = 9999

# Tcl Server 脚本模板（唯一权威实现，遵循 TCP_PROTOCOL.md 规范）
TCL_SERVER_TEMPLATE = '''# GateFlow Tcl Server
# Auto-generated by GateFlow installation
# Protocol Version: {version}

# 设置 UTF-8 编码，确保中文正常显示
encoding system utf-8

# 协议版本标识
set ::gateflow_protocol_version "{version}"

# TCP 服务器配置
set gateflow_server_port {port}
set gateflow_server_running 1

# 处理客户端连接
proc gateflow_accept_connection {{channel addr port}} {{
    puts "GateFlow: Client connected from $addr:$port"
    fconfigure $channel -translation binary -buffering none -encoding utf-8
    
    # 设置文件事件处理
    fileevent $channel readable [list gateflow_handle_client $channel]
}}

# 处理客户端请求
proc gateflow_handle_client {{channel}} {{
    if {{[eof $channel]}} {{
        puts "GateFlow: Client disconnected"
        close $channel
        return
    }}
    
    set line [gets $channel]
    
    # 忽略空命令
    set line [string trim $line]
    if {{$line eq ""}} return
    
    # 执行 Tcl 命令
    puts "GateFlow: Executing: $line"
    if {{[catch {{uplevel #0 $line}} result]}} {{
        # 命令执行失败，返回错误信息
        set response "ERROR: $result"
    }} else {{
        # 命令执行成功，返回结果
        if {{$result eq ""}} {{
            set response "OK:"
        }} else {{
            set response "OK: $result"
        }}
    }}
    
    # 发送响应（确保以换行符结尾）
    puts $channel $response
    # 发送提示符，让客户端知道命令执行完成
    # 提示符格式: "% " 后跟换行符
    puts $channel "% "
    flush $channel
}}

# 启动服务器
proc gateflow_start_server {{{{port {port}}}}} {{
    puts "GateFlow Tcl Server starting on port $port..."
    puts "GateFlow: Protocol version $::gateflow_protocol_version"
    
    if {{[catch {{socket -server gateflow_accept_connection $port}} server_socket]}} {{
        puts "GateFlow Error: Failed to start server - $server_socket"
        return 0
    }}
    
    puts "GateFlow Tcl Server started successfully"
    puts "GateFlow: Listening on port $port"
    return 1
}}

# 自动启动服务器
if {{[gateflow_start_server {port}]}} {{
    # 进入事件循环，保持服务器运行
    vwait forever
}}
'''

NON_BLOCKING_STARTUP_TEMPLATE = """
# Start the server without blocking Vivado GUI startup.
gateflow_start_server {port}
"""

BLOCKING_STARTUP_PATTERN = r"#.*?if \{\[gateflow_start_server __PORT__\]\} \{.*?vwait forever\s*\}"


@dataclass
class VivadoInstallation:
    """Vivado 安装信息"""
    version: str
    path: Path
    executable: Path
    init_tcl_path: Path | None = None


class VivadoDetector:
    """Vivado 安装检测器"""
    
    WINDOWS_DEFAULT_PATHS = [
        Path("C:/Xilinx/Vivado"),
        Path("D:/Xilinx/Vivado"),
        Path("E:/Xilinx/Vivado"),
    ]
    
    @classmethod
    def detect_all_installations(cls) -> list[VivadoInstallation]:
        """
        检测所有 Vivado 安装
        
        Returns:
            VivadoInstallation 列表
        """
        installations = []
        
        # 从注册表检测
        if sys.platform == "win32":
            registry_installations = cls.detect_from_registry()
            installations.extend(registry_installations)
        
        # 从默认路径检测
        for base_path in cls.WINDOWS_DEFAULT_PATHS:
            if base_path.exists():
                for version_dir in sorted(base_path.iterdir(), reverse=True):
                    if version_dir.is_dir() and cls._is_version_dir(version_dir):
                        installation = cls.validate_installation(version_dir)
                        if installation:
                            # 避免重复添加
                            if not any(inst.path == installation.path for inst in installations):
                                installations.append(installation)
        
        # 按版本排序（最新的在前）
        installations.sort(key=lambda x: x.version, reverse=True)
        
        return installations
    
    @classmethod
    def detect_latest_installation(cls) -> VivadoInstallation | None:
        """
        检测最新版本的 Vivado
        
        Returns:
            最新的 VivadoInstallation 或 None
        """
        installations = cls.detect_all_installations()
        return installations[0] if installations else None
    
    @classmethod
    def detect_from_registry(cls) -> list[VivadoInstallation]:
        """
        从 Windows 注册表检测 Vivado
        
        Returns:
            VivadoInstallation 列表
        """
        installations = []
        
        if sys.platform != "win32":
            return installations
        
        try:
            # 尝试多个注册表位置
            reg_paths = [
                (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Xilinx\Vivado"),
                (winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\WOW6432Node\Xilinx\Vivado"),
                (winreg.HKEY_CURRENT_USER, r"SOFTWARE\Xilinx\Vivado"),
            ]
            
            for hkey, subkey in reg_paths:
                try:
                    with winreg.OpenKey(hkey, subkey) as key:
                        # 枚举版本子键
                        idx = 0
                        while True:
                            try:
                                version_name = winreg.EnumKey(key, idx)
                                try:
                                    with winreg.OpenKey(key, version_name) as version_key:
                                        install_path, _ = winreg.QueryValueEx(version_key, "InstallDir")
                                        if install_path:
                                            installation = cls.validate_installation(Path(install_path))
                                            if installation:
                                                # 避免重复添加
                                                if not any(inst.path == installation.path for inst in installations):
                                                    installations.append(installation)
                                except (FileNotFoundError, OSError):
                                    pass
                                idx += 1
                            except OSError:
                                break
                except (FileNotFoundError, OSError):
                    continue
                    
        except ImportError:
            logger.warning("无法导入 winreg 模块，跳过注册表检测")
        
        return installations
    
    @classmethod
    def validate_installation(cls, path: Path) -> VivadoInstallation | None:
        """
        验证 Vivado 安装路径
        
        Args:
            path: Vivado 安装路径
        
        Returns:
            VivadoInstallation 或 None
        """
        # 检查路径是否存在
        if not path.exists():
            logger.debug(f"路径不存在: {path}")
            return None
        
        # 检查可执行文件
        if sys.platform == "win32":
            executable = path / "bin" / "vivado.bat"
            if not executable.exists():
                executable = path / "bin" / "vivado.exe"
        else:
            executable = path / "bin" / "vivado"
        
        if not executable.exists():
            logger.debug(f"Vivado 可执行文件不存在: {executable}")
            return None
        
        # 提取版本号
        version = path.name
        if not cls._is_version_dir(path):
            # 尝试从版本文件读取
            version_file = path / "version.txt"
            if version_file.exists():
                version = version_file.read_text(encoding='utf-8').strip()
            else:
                version = "unknown"
        
        # 查找 Vivado_init.tcl 路径
        init_tcl_path = cls._find_init_tcl(path)
        
        return VivadoInstallation(
            version=version,
            path=path,
            executable=executable,
            init_tcl_path=init_tcl_path,
        )
    
    @classmethod
    def _is_version_dir(cls, path: Path) -> bool:
        """检查是否为版本目录"""
        # 版本目录名格式：YYYY.X
        pattern = r'^\d{4}\.\d{1,2}$'
        return bool(re.match(pattern, path.name))
    
    @classmethod
    def _find_init_tcl(cls, vivado_path: Path) -> Path | None:
        """
        查找 Vivado_init.tcl 文件路径
        
        Vivado_init.tcl 可能位于以下位置：
        1. %APPDATA%/Xilinx/Vivado/Vivado_init.tcl (用户配置)
        2. <Vivado>/scripts/Vivado_init.tcl (安装目录)
        
        Args:
            vivado_path: Vivado 安装路径
        
        Returns:
            Vivado_init.tcl 路径或 None
        """
        # 用户配置目录（优先）
        if sys.platform == "win32":
            import os
            appdata = os.environ.get('APPDATA')
            if appdata:
                user_init_tcl = Path(appdata) / "Xilinx" / "Vivado" / "Vivado_init.tcl"
                return user_init_tcl
        
        # 安装目录
        install_init_tcl = vivado_path / "scripts" / "Vivado_init.tcl"
        if install_init_tcl.exists():
            return install_init_tcl
        
        # 默认返回用户配置路径（即使不存在）
        if sys.platform == "win32":
            import os
            appdata = os.environ.get('APPDATA')
            if appdata:
                return Path(appdata) / "Xilinx" / "Vivado" / "Vivado_init.tcl"
        
        return None


class TclServerInstaller:
    """Tcl Server 安装器"""
    
    INIT_TCL_FILENAME = "Vivado_init.tcl"
    GATEFLOW_MARKER_START = "# ===== GateFlow Tcl Server BEGIN ====="
    GATEFLOW_MARKER_END = "# ===== GateFlow Tcl Server END ====="
    
    def __init__(self, vivado_installation: VivadoInstallation | object = None):
        """
        初始化安装器
        
        Args:
            vivado_installation: Vivado 安装信息（可选，用于安装到 Vivado_init.tcl）
        """
        self.vivado = self._normalize_installation(vivado_installation)

    @staticmethod
    def _normalize_installation(
        vivado_installation: VivadoInstallation | object | None,
    ) -> VivadoInstallation | None:
        """Accept both VivadoInstallation and VivadoInfo-like objects."""
        if vivado_installation is None:
            return None

        if isinstance(vivado_installation, VivadoInstallation):
            return vivado_installation

        install_path = getattr(vivado_installation, "path", None) or getattr(
            vivado_installation, "install_path", None
        )
        executable = getattr(vivado_installation, "executable", None)
        version = getattr(vivado_installation, "version", "unknown")
        init_tcl_path = getattr(vivado_installation, "init_tcl_path", None)

        if install_path is None or executable is None:
            raise ValueError("无效的 Vivado 安装信息，缺少路径或可执行文件")

        install_path = Path(install_path)
        executable = Path(executable)
        if init_tcl_path is None:
            init_tcl_path = VivadoDetector._find_init_tcl(install_path)
        else:
            init_tcl_path = Path(init_tcl_path)

        return VivadoInstallation(
            version=str(version),
            path=install_path,
            executable=executable,
            init_tcl_path=init_tcl_path,
        )
    
    def generate_script(
        self,
        port: int = DEFAULT_PORT,
        version: str = "1.0",
        blocking: bool = True,
    ) -> str:
        """
        生成 Tcl Server 脚本
        
        Args:
            port: TCP 端口号
            version: 脚本版本号
        
        Returns:
            Tcl Server 脚本内容
        """
        script = TCL_SERVER_TEMPLATE.format(port=port, version=version)
        if blocking:
            return script

        return re.sub(
            BLOCKING_STARTUP_PATTERN.replace("__PORT__", str(port)),
            NON_BLOCKING_STARTUP_TEMPLATE.format(port=port).strip(),
            script,
            flags=re.DOTALL,
        )
    
    def install_to_vivado(self, port: int = DEFAULT_PORT) -> bool:
        """
        安装到 Vivado_init.tcl
        
        Args:
            port: TCP 端口号
        
        Returns:
            安装是否成功
        """
        if self.vivado is None:
            logger.error("未提供 Vivado 安装信息")
            return False
        
        return self.install(port)
    
    def uninstall_from_vivado(self) -> bool:
        """
        从 Vivado_init.tcl 移除
        
        Returns:
            卸载是否成功
        """
        if self.vivado is None:
            logger.error("未提供 Vivado 安装信息")
            return False
        
        return self.uninstall()
    
    def install(self, port: int = DEFAULT_PORT) -> bool:
        """
        安装 Tcl Server 到 Vivado
        
        Args:
            port: TCP 端口号
        
        Returns:
            安装是否成功
        """
        try:
            # 获取 Vivado_init.tcl 路径
            init_tcl_path = self.get_init_tcl_path()
            if init_tcl_path is None:
                logger.error("无法确定 Vivado_init.tcl 路径")
                return False
            
            # 创建目录（如果不存在）
            init_tcl_path.parent.mkdir(parents=True, exist_ok=True)
            
            # 创建文件（如果不存在）
            if not self._create_init_tcl_if_not_exists():
                logger.error("无法创建 Vivado_init.tcl")
                return False
            
            # 读取现有内容
            content = self._read_init_tcl()
            if content is None:
                logger.error("无法读取 Vivado_init.tcl")
                return False
            
            # 检查是否已安装
            if self.is_installed():
                logger.info("Tcl Server 已安装，将更新配置")
                content = self._remove_server_code(content)
            
            # 生成服务器代码
            server_code = self._generate_server_code(port, blocking=False)
            
            # 插入服务器代码
            new_content = self._insert_server_code(content, server_code)
            
            # 写入文件
            if self._write_init_tcl(new_content):
                logger.info(f"成功安装 Tcl Server 到 {init_tcl_path}")
                logger.info(f"服务器将在 Vivado 启动时自动运行于端口 {port}")
                return True
            else:
                logger.error("写入 Vivado_init.tcl 失败")
                return False
                
        except Exception as e:
            logger.exception(f"安装 Tcl Server 失败: {e}")
            return False
    
    def uninstall(self) -> bool:
        """
        卸载 Tcl Server
        
        Returns:
            卸载是否成功
        """
        try:
            # 获取 Vivado_init.tcl 路径
            init_tcl_path = self.get_init_tcl_path()
            if init_tcl_path is None or not init_tcl_path.exists():
                logger.info("Vivado_init.tcl 不存在，无需卸载")
                return True
            
            # 读取现有内容
            content = self._read_init_tcl()
            if content is None:
                logger.error("无法读取 Vivado_init.tcl")
                return False
            
            # 检查是否已安装
            if not self.is_installed():
                logger.info("Tcl Server 未安装，无需卸载")
                return True
            
            # 移除服务器代码
            new_content = self._remove_server_code(content)
            
            # 写入文件
            if self._write_init_tcl(new_content):
                logger.info(f"成功卸载 Tcl Server")
                return True
            else:
                logger.error("写入 Vivado_init.tcl 失败")
                return False
                
        except Exception as e:
            logger.exception(f"卸载 Tcl Server 失败: {e}")
            return False
    
    def is_installed(self) -> bool:
        """
        检查是否已安装
        
        Returns:
            是否已安装
        """
        init_tcl_path = self.get_init_tcl_path()
        if init_tcl_path is None or not init_tcl_path.exists():
            return False
        
        content = self._read_init_tcl()
        if content is None:
            return False
        
        return self.GATEFLOW_MARKER_START in content
    
    def get_init_tcl_path(self) -> Path | None:
        """
        获取 Vivado_init.tcl 路径
        
        Returns:
            Vivado_init.tcl 文件路径
        """
        return self.vivado.init_tcl_path
    
    def _create_init_tcl_if_not_exists(self) -> bool:
        """如果不存在则创建 Vivado_init.tcl"""
        init_tcl_path = self.get_init_tcl_path()
        if init_tcl_path is None:
            return False
        
        if init_tcl_path.exists():
            return True
        
        try:
            # 创建目录
            init_tcl_path.parent.mkdir(parents=True, exist_ok=True)
            
            # 创建文件并写入基本内容
            header = """# Vivado Initialization Script
# This file is automatically loaded when Vivado starts

"""
            init_tcl_path.write_text(header, encoding='utf-8')
            logger.info(f"已创建 {init_tcl_path}")
            return True
        except Exception as e:
            logger.error(f"创建 Vivado_init.tcl 失败: {e}")
            return False
    
    def _read_init_tcl(self) -> str | None:
        """读取 Vivado_init.tcl 内容"""
        init_tcl_path = self.get_init_tcl_path()
        if init_tcl_path is None or not init_tcl_path.exists():
            return None
        
        try:
            return init_tcl_path.read_text(encoding='utf-8')
        except Exception as e:
            logger.error(f"读取 Vivado_init.tcl 失败: {e}")
            return None
    
    def _write_init_tcl(self, content: str) -> bool:
        """写入 Vivado_init.tcl 内容"""
        init_tcl_path = self.get_init_tcl_path()
        if init_tcl_path is None:
            return False
        
        try:
            init_tcl_path.write_text(content, encoding='utf-8')
            return True
        except Exception as e:
            logger.error(f"写入 Vivado_init.tcl 失败: {e}")
            return False
    
    def _generate_server_code(self, port: int, blocking: bool = False) -> str:
        """
        生成 Tcl Server 代码
        
        Args:
            port: TCP 端口号
        
        Returns:
            Tcl Server 代码
        """
        # 使用标记包裹服务器代码
        server_code = self.generate_script(port=port, blocking=blocking)
        
        wrapped_code = f"""
{self.GATEFLOW_MARKER_START}
{server_code}
{self.GATEFLOW_MARKER_END}
"""
        return wrapped_code
    
    def _insert_server_code(self, content: str, server_code: str) -> str:
        """
        在 Vivado_init.tcl 中插入 Server 代码
        
        Args:
            content: 原始内容
            server_code: Server 代码
        
        Returns:
            修改后的内容
        """
        # 在文件末尾添加服务器代码
        # 确保前面有换行符
        if content and not content.endswith('\n'):
            content += '\n'
        
        return content + server_code
    
    def _remove_server_code(self, content: str) -> str:
        """
        从 Vivado_init.tcl 中移除 Server 代码
        
        Args:
            content: 原始内容
        
        Returns:
            修改后的内容
        """
        # 使用正则表达式移除标记之间的内容
        pattern = re.escape(self.GATEFLOW_MARKER_START) + r'.*?' + re.escape(self.GATEFLOW_MARKER_END)
        new_content = re.sub(pattern, '', content, flags=re.DOTALL)
        
        # 清理多余的空行
        new_content = re.sub(r'\n{3,}', '\n\n', new_content)
        
        return new_content.strip() + '\n'


# 便捷函数
def install_tcl_server(port: int = DEFAULT_PORT, vivado_path: Path | None = None) -> bool:
    """
    安装 Tcl Server 到 Vivado
    
    Args:
        port: TCP 端口号
        vivado_path: Vivado 安装路径，如果为 None 则自动检测
    
    Returns:
        安装是否成功
    """
    # 获取 Vivado 安装信息
    if vivado_path:
        installation = VivadoDetector.validate_installation(vivado_path)
        if installation is None:
            logger.error(f"无效的 Vivado 路径: {vivado_path}")
            return False
    else:
        installation = VivadoDetector.detect_latest_installation()
        if installation is None:
            logger.error("未找到 Vivado 安装")
            return False
    
    # 创建安装器并安装
    installer = TclServerInstaller(installation)
    return installer.install(port)


def uninstall_tcl_server(vivado_path: Path | None = None) -> bool:
    """
    卸载 Tcl Server
    
    Args:
        vivado_path: Vivado 安装路径，如果为 None 则自动检测
    
    Returns:
        卸载是否成功
    """
    # 获取 Vivado 安装信息
    if vivado_path:
        installation = VivadoDetector.validate_installation(vivado_path)
        if installation is None:
            logger.error(f"无效的 Vivado 路径: {vivado_path}")
            return False
    else:
        installation = VivadoDetector.detect_latest_installation()
        if installation is None:
            logger.error("未找到 Vivado 安装")
            return False
    
    # 创建安装器并卸载
    installer = TclServerInstaller(installation)
    return installer.uninstall()


def list_vivado_installations() -> list[VivadoInstallation]:
    """
    列出所有 Vivado 安装
    
    Returns:
        VivadoInstallation 列表
    """
    return VivadoDetector.detect_all_installations()
